#!/usr/bin/env python3
"""Tests for block-ai-attribution.py.

Self-contained (no pytest needed): feeds PreToolUse payloads to the hook as a
subprocess and asserts the exit code. Exit 0 = allowed, 2 = blocked.
Run: python3 hooks/test_block_ai_attribution.py
"""
import json
import os
import subprocess
import sys
import tempfile

HOOK = os.path.join(os.path.dirname(os.path.abspath(__file__)), "block-ai-attribution.py")

ALLOW, BLOCK = 0, 2


def run(payload):
    p = subprocess.run(
        [sys.executable, HOOK],
        input=json.dumps(payload),
        capture_output=True, text=True,
    )
    return p.returncode


def bash(command):
    return {"tool_name": "Bash", "tool_input": {"command": command}}


def main():
    # A temp file holding an attributed message, for the -F case.
    fd, msg_file = tempfile.mkstemp(suffix=".txt")
    with os.fdopen(fd, "w") as fh:
        fh.write("feat: add thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n")
    clean_fd, clean_file = tempfile.mkstemp(suffix=".txt")
    with os.fdopen(clean_fd, "w") as fh:
        fh.write("feat: add thing\n\nthis is a normal message\n")

    cases = [
        # (label, payload, expected_exit)
        ("clean -m", bash('git commit -m "fix: resolve login bug"'), ALLOW),
        ("clean mentions url non-attribution",
         bash('git commit -m "Add claude.ai/code OAuth login button"'), ALLOW),
        ("clean mentions claude in subject",
         bash('git commit -m "fix claude integration timeout"'), ALLOW),
        ("co-authored-by claude",
         bash('git commit -m "x" -m "Co-Authored-By: Claude <noreply@anthropic.com>"'), BLOCK),
        ("co-authored-by copilot",
         bash('git commit -m "x\n\nCo-authored-by: GitHub Copilot <bot@github.com>"'), BLOCK),
        ("generated with claude code",
         bash('git commit -m "x" -m "Generated with Claude Code"'), BLOCK),
        ("generated by claude",
         bash('git commit -m "x\n\nGenerated by Claude"'), BLOCK),
        ("robot emoji generated",
         bash('git commit -m "x\n\n\U0001f916 Generated with Claude Code"'), BLOCK),
        ("attribution link",
         bash('git commit -m "x\n\nhttps://claude.ai/code/session_abc"'), BLOCK),
        ("heredoc attributed",
         bash("git commit -F - <<'EOF'\nfeat: x\n\nCo-Authored-By: Claude\nEOF"), BLOCK),
        ("heredoc clean",
         bash("git commit -F - <<'EOF'\nfeat: x\n\njust a normal body\nEOF"), ALLOW),
        ("-F file attributed", bash('git commit -F %s' % msg_file), BLOCK),
        ("-F file clean", bash('git commit -F %s' % clean_file), ALLOW),
        ("non-commit git config",
         bash('git config commit.template ~/.gitmessage'), ALLOW),
        ("non-commit git log grep",
         bash('git log --grep commit --oneline'), ALLOW),
        ("git -C dir commit attributed",
         bash('git -C /repo commit -m "x\n\nCo-Authored-By: Claude"'), BLOCK),
        ("non-git bash", bash("ls -la"), ALLOW),
        ("echo mentioning git commit", bash('echo "how to git commit"'), ALLOW),
        ("non-Bash tool", {"tool_name": "Edit", "tool_input": {"file_path": "x"}}, ALLOW),
        ("malformed payload", "not json at all", ALLOW),
    ]

    failures = []
    for label, payload, expected in cases:
        if isinstance(payload, str):
            # malformed-input case: feed raw text
            p = subprocess.run([sys.executable, HOOK], input=payload,
                               capture_output=True, text=True)
            got = p.returncode
        else:
            got = run(payload)
        ok = got == expected
        print(f"  [{'PASS' if ok else 'FAIL'}] {label}: expected {expected}, got {got}")
        if not ok:
            failures.append(label)

    os.remove(msg_file)
    os.remove(clean_file)

    if failures:
        print(f"\n{len(failures)} FAILED: {failures}")
        sys.exit(1)
    print(f"\nAll {len(cases)} cases passed.")


if __name__ == "__main__":
    main()
